"""create core tables

Revision ID: 1e6859fa4e56
Revises:
Create Date: 2026-08-19 13:01:31.967154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e6859fa4e56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector's Vector column type needs this before document_chunks is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('filing_type', sa.String(), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('accession_number', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', chunk_text)", persisted=True), nullable=True),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunks_document_chunk')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_threads',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role in ('user', 'assistant')", name='ck_chat_messages_role'),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_citations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Retrieval indexes: HNSW for pgvector semantic search, GIN for full-text.
    op.execute(
        "CREATE INDEX ix_document_chunks_embedding_hnsw "
        "ON document_chunks USING hnsw (embedding vector_cosine_ops)"
    )
    op.create_index(
        "ix_document_chunks_search_vector",
        "document_chunks",
        ["search_vector"],
        postgresql_using="gin",
    )

    # Row-level security: analysts only see their own chat data.
    # source_documents / document_chunks are shared corpus data, readable by
    # any authenticated user; writes to those two happen via the service-role
    # key (ingestion), which bypasses RLS entirely.
    for table in (
        "users",
        "chat_threads",
        "chat_messages",
        "message_citations",
        "source_documents",
        "document_chunks",
    ):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")

    op.execute("CREATE POLICY users_select_own ON users FOR SELECT USING (id = auth.uid())")
    op.execute("CREATE POLICY users_update_own ON users FOR UPDATE USING (id = auth.uid())")

    op.execute(
        "CREATE POLICY chat_threads_select_own ON chat_threads "
        "FOR SELECT USING (user_id = auth.uid())"
    )
    op.execute(
        "CREATE POLICY chat_threads_insert_own ON chat_threads "
        "FOR INSERT WITH CHECK (user_id = auth.uid())"
    )
    op.execute(
        "CREATE POLICY chat_threads_update_own ON chat_threads "
        "FOR UPDATE USING (user_id = auth.uid())"
    )
    op.execute(
        "CREATE POLICY chat_threads_delete_own ON chat_threads "
        "FOR DELETE USING (user_id = auth.uid())"
    )

    op.execute(
        "CREATE POLICY chat_messages_select_own ON chat_messages "
        "FOR SELECT USING ("
        "  EXISTS ("
        "    SELECT 1 FROM chat_threads"
        "    WHERE chat_threads.id = chat_messages.thread_id"
        "    AND chat_threads.user_id = auth.uid()"
        "  )"
        ")"
    )
    op.execute(
        "CREATE POLICY chat_messages_insert_own ON chat_messages "
        "FOR INSERT WITH CHECK ("
        "  EXISTS ("
        "    SELECT 1 FROM chat_threads"
        "    WHERE chat_threads.id = chat_messages.thread_id"
        "    AND chat_threads.user_id = auth.uid()"
        "  )"
        ")"
    )

    op.execute(
        "CREATE POLICY message_citations_select_own ON message_citations "
        "FOR SELECT USING ("
        "  EXISTS ("
        "    SELECT 1 FROM chat_messages"
        "    JOIN chat_threads ON chat_threads.id = chat_messages.thread_id"
        "    WHERE chat_messages.id = message_citations.message_id"
        "    AND chat_threads.user_id = auth.uid()"
        "  )"
        ")"
    )

    op.execute(
        "CREATE POLICY source_documents_select_authenticated ON source_documents "
        "FOR SELECT USING (auth.role() = 'authenticated')"
    )
    op.execute(
        "CREATE POLICY document_chunks_select_authenticated ON document_chunks "
        "FOR SELECT USING (auth.role() = 'authenticated')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Dropping each table also drops its indexes and RLS policies.
    op.drop_table('message_citations')
    op.drop_table('chat_messages')
    op.drop_table('chat_threads')
    op.drop_table('users')
    op.drop_table('document_chunks')
    op.drop_table('source_documents')
    # ### end Alembic commands ###

    op.execute("DROP EXTENSION IF EXISTS vector")
